import { TreeData } from './types';

export const CARD_WIDTH = 240;
export const CARD_HEIGHT = 185;

export const defaultTreeData: TreeData = {
  nodes: [
    {
      id: "node_1",
      branch: "paternal",
      name: "Prithviraj Patel",
      relationship_to_root: "Great-Grandfather",
      gender: "male",
      marital_status: "married",
      status: "deceased",
      dob: "1898-03-12",
      dod: "1982-11-20",
      gotra: "Kashyap",
      bansa: "Suryavansh",
      age: 84,
      profession: "Landowner & Zamindar",
      phone: "",
      address: "Barpali, Bargarh",
      notes: "Founding elder of the Barpali lineage.",
      x: 360,
      y: 50
    },
    {
      id: "node_2",
      branch: "paternal",
      name: "Dinanath Patel",
      relationship_to_root: "Grandfather",
      gender: "male",
      marital_status: "married",
      status: "deceased",
      dob: "1932-08-15",
      dod: "2010-04-15",
      gotra: "Kashyap",
      bansa: "Suryavansh",
      age: 78,
      profession: "Headmaster & Scholar",
      phone: "",
      address: "Bargarh, Odisha",
      notes: "Prominent educator and village elder.",
      x: 360,
      y: 290
    },
    {
      id: "node_3",
      branch: "paternal",
      name: "Suresh Patel",
      relationship_to_root: "Father",
      gender: "male",
      marital_status: "married",
      status: "alive",
      dob: "1968-01-10",
      gotra: "Kashyap",
      bansa: "Suryavansh",
      age: 58,
      profession: "Agricultural Business",
      phone: "+91 94370 12345",
      address: "Sambalpur, Odisha",
      notes: "Active community leader.",
      x: 360,
      y: 540
    },
    {
      id: "node_4",
      branch: "paternal",
      name: "Husband / Self",
      relationship_to_root: "Root (Self)",
      gender: "male",
      marital_status: "married",
      status: "alive",
      dob: "1997-05-18",
      gotra: "Kashyap",
      bansa: "Suryavansh",
      age: 29,
      profession: "Software Architect",
      phone: "+91 98610 54321",
      address: "Bhubaneswar, Odisha",
      notes: "Custodian of digital Vanshavali archive.",
      x: 360,
      y: 800
    },
    {
      id: "node_5",
      branch: "maternal",
      name: "Pooja Patel",
      relationship_to_root: "1st Wife",
      gender: "female",
      marital_status: "married",
      status: "alive",
      dob: "1998-11-09",
      gotra: "Bharadwaj",
      bansa: "Chandravansh",
      age: 28,
      profession: "Associate Professor",
      phone: "+91 98610 11111",
      address: "Bhubaneswar, Odisha",
      notes: "Eldest daughter of Cuttack Bharadwaj gotra lineage.",
      x: 660,
      y: 800
    },
    {
      id: "node_6",
      branch: "maternal",
      name: "Alok Panda",
      relationship_to_root: "1st Wife's Brother",
      gender: "male",
      marital_status: "unmarried",
      status: "alive",
      dob: "1995-09-04",
      gotra: "Bharadwaj",
      bansa: "Chandravansh",
      age: 31,
      profession: "Architect & Urban Planner",
      phone: "+91 98610 22222",
      address: "Rourkela, Odisha",
      notes: "Brother-in-law to Root.",
      x: 960,
      y: 800
    },
    {
      id: "node_7",
      branch: "maternal",
      name: "Gopal Panda",
      relationship_to_root: "Father-in-Law (1st Wife)",
      gender: "male",
      marital_status: "married",
      status: "alive",
      dob: "1965-06-21",
      gotra: "Bharadwaj",
      bansa: "Chandravansh",
      age: 61,
      profession: "Retired Gazetted Officer",
      phone: "+91 94371 33333",
      address: "Cuttack, Odisha",
      notes: "Patriarch of Bharadwaj in-law branch.",
      x: 800,
      y: 540
    },
    {
      id: "node_8",
      branch: "maternal",
      name: "Sunita Patel",
      relationship_to_root: "2nd Wife",
      gender: "female",
      marital_status: "married",
      status: "alive",
      dob: "2000-04-25",
      gotra: "Sandilya",
      bansa: "Nagavansh",
      age: 26,
      profession: "Physician (MD)",
      phone: "+91 98610 44444",
      address: "Jharsuguda, Odisha",
      notes: "Second spouse with distinct Gotra heritage.",
      x: 60,
      y: 800
    },
    {
      id: "node_9",
      branch: "paternal",
      name: "Aarav Patel",
      relationship_to_root: "Son (Next Gen)",
      gender: "male",
      marital_status: "unmarried",
      status: "alive",
      dob: "2022-07-14",
      gotra: "Kashyap",
      bansa: "Suryavansh",
      age: 4,
      profession: "Student",
      phone: "",
      address: "Bhubaneswar, Odisha",
      notes: "Latest generation scion.",
      x: 510,
      y: 1060
    }
  ],
  links: [
    { id: "l1", source: "node_1", target: "node_2", type: "parent" },
    { id: "l2", source: "node_2", target: "node_3", type: "parent" },
    { id: "l3", source: "node_3", target: "node_4", type: "parent" },
    { id: "l4", source: "node_4", target: "node_5", type: "spouse" },
    { id: "l5", source: "node_4", target: "node_8", type: "spouse" },
    { id: "l6", source: "node_5", target: "node_6", type: "sibling" },
    { id: "l7", source: "node_7", target: "node_5", type: "parent" },
    { id: "l8", source: "node_7", target: "node_6", type: "parent" },
    { id: "l9", source: "node_4", target: "node_9", type: "parent" },
    { id: "l10", source: "node_5", target: "node_9", type: "parent" }
  ]
};
